
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const CartItemSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	customerId: Joi.number().integer().required().messages({
        'any.required': 'customerId is required.',
        'number.base': 'customerId must be a valid integer.',
      }),
 	productId: Joi.number().integer().required().messages({
        'any.required': 'productId is required.',
        'number.base': 'productId must be a valid integer.',
      }),
 	quantity: Joi.string().trim().required().messages({
        'any.required': 'quantity is required.',
        'string.empty': 'quantity must be a valid decimal.',
      }),
 	price: Joi.string().trim().required().messages({
        'any.required': 'price is required.',
        'string.empty': 'price must be a valid decimal.',
      })
});


/** Field references for clean, type-safe access */
const CartItemField = {
    Id: 'id',
    CustomerId: 'customer_id',
    ProductId: 'product_id',
    Quantity: 'quantity',
    Price: 'price',
    All: ['id', 'customer_id', 'product_id', 'quantity', 'price'],
};


module.exports = {
  CartItemSchema,
  CartItemField, 
};
