
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const CustomerSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	fullname: Joi.string().trim().required().messages({
        'any.required': 'fullname is required.',
        'string.empty': 'fullname must be a valid string.',
      }),
 	email: Joi.string().trim().required().messages({
        'any.required': 'email is required.',
        'string.empty': 'email must be a valid string.',
      }),
 	customerType: Joi.string().trim().required().messages({
        'any.required': 'customerType is required.',
        'string.empty': 'customerType must be a valid enum.',
      }),
 	address: Joi.string().trim().required().messages({
        'any.required': 'address is required.',
        'string.empty': 'address must be a valid string.',
      }),
 	latitude: Joi.string().trim().required().messages({
        'any.required': 'latitude is required.',
        'string.empty': 'latitude must be a valid decimal.',
      }),
 	longitude: Joi.string().trim().required().messages({
        'any.required': 'longitude is required.',
        'string.empty': 'longitude must be a valid decimal.',
      }),
 	password: Joi.string().trim().required().messages({
        'any.required': 'password is required.',
        'string.empty': 'password must be a valid text.',
      })
});


/** Field references for clean, type-safe access */
const CustomerField = {
    Id: 'id',
    Fullname: 'fullname',
    Email: 'email',
    CustomerType: 'customer_type',
    Address: 'address',
    Latitude: 'latitude',
    Longitude: 'longitude',
    Password: 'password',
    Createddate: 'createddate',
    All: ['id', 'fullname', 'email', 'customer_type', 'address', 'latitude', 'longitude', 'password', 'createddate'],
};


module.exports = {
  CustomerSchema,
  CustomerField, 
};
