
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const CustomerSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	fullname: Joi.string().trim().required().messages({
        'any.required': 'fullname is required.',
        'string.empty': 'fullname must be a valid string.',
      }),
 	contact: Joi.string().trim().required().messages({
        'any.required': 'contact is required.',
        'string.empty': 'contact must be a valid string.',
      }),
 	email: Joi.string().trim().required().messages({
        'any.required': 'email is required.',
        'string.empty': 'email must be a valid string.',
      }),
 	address: Joi.string().trim().required().messages({
        'any.required': 'address is required.',
        'string.empty': 'address must be a valid string.',
      }),
 	latitude: Joi.string().trim().required().messages({
        'any.required': 'latitude is required.',
        'string.empty': 'latitude must be a valid decimal.',
      }),
 	longitude: Joi.string().trim().required().messages({
        'any.required': 'longitude is required.',
        'string.empty': 'longitude must be a valid decimal.',
      }),
 	username: Joi.string().trim().required().messages({
        'any.required': 'username is required.',
        'string.empty': 'username must be a valid string.',
      }),
 	password: Joi.string().trim().required().messages({
        'any.required': 'password is required.',
        'string.empty': 'password must be a valid text.',
      }),
 	isRegistered: Joi.boolean().required().messages({
        'any.required': 'isRegistered is required.',
        'boolean.base': 'isRegistered must be a valid boolean.',
      })
});


/** Field references for clean, type-safe access */
const CustomerField = {
    Id: 'id',
    Fullname: 'fullname',
    Contact: 'contact',
    Email: 'email',
    Address: 'address',
    Latitude: 'latitude',
    Longitude: 'longitude',
    Username: 'username',
    Password: 'password',
    IsRegistered: 'is_registered',
    Createddate: 'createddate',
    All: ['id', 'fullname', 'contact', 'email', 'address', 'latitude', 'longitude', 'username', 'password', 'is_registered', 'createddate'],
};


module.exports = {
  CustomerSchema,
  CustomerField, 
};
