
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const DeliveryImageSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	deliveryActivityId: Joi.number().integer().required().messages({
        'any.required': 'deliveryActivityId is required.',
        'number.base': 'deliveryActivityId must be a valid integer.',
      }),
 	type: Joi.string().trim().required().messages({
        'any.required': 'type is required.',
        'string.empty': 'type must be a valid enum.',
      }),
 	image: Joi.string().trim().required().messages({
        'any.required': 'image is required.',
        'string.empty': 'image must be a valid text.',
      })
});


/** Field references for clean, type-safe access */
const DeliveryImageField = {
    Id: 'id',
    DeliveryActivityId: 'delivery_activity_id',
    Type: 'type',
    Image: 'image',
    Createddate: 'createddate',
    All: ['id', 'delivery_activity_id', 'type', 'image', 'createddate'],
};


module.exports = {
  DeliveryImageSchema,
  DeliveryImageField, 
};
