
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const DeliveryActivitySchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	deliveryId: Joi.number().integer().required().messages({
        'any.required': 'deliveryId is required.',
        'number.base': 'deliveryId must be a valid integer.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
 	remarks: Joi.string().trim().required().messages({
        'any.required': 'remarks is required.',
        'string.empty': 'remarks must be a valid text.',
      })
});


/** Field references for clean, type-safe access */
const DeliveryActivityField = {
    Id: 'id',
    DeliveryId: 'delivery_id',
    Status: 'status',
    Remarks: 'remarks',
    Createddate: 'createddate',
    All: ['id', 'delivery_id', 'status', 'remarks', 'createddate'],
};


module.exports = {
  DeliveryActivitySchema,
  DeliveryActivityField, 
};
