
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const DeliverySchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	orderId: Joi.number().integer().required().messages({
        'any.required': 'orderId is required.',
        'number.base': 'orderId must be a valid integer.',
      }),
 	riderId: Joi.number().integer().required().messages({
        'any.required': 'riderId is required.',
        'number.base': 'riderId must be a valid integer.',
      }),
 	date: Joi.string().isoDate().required().messages({
        'any.required': 'date is required.',
        'string.empty': 'date must be a valid date.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const DeliveryField = {
    Id: 'id',
    OrderId: 'order_id',
    RiderId: 'rider_id',
    Date: 'date',
    Status: 'status',
    All: ['id', 'order_id', 'rider_id', 'date', 'status'],
};


module.exports = {
  DeliverySchema,
  DeliveryField, 
};
