
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const InventorySchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	productId: Joi.number().integer().required().messages({
        'any.required': 'productId is required.',
        'number.base': 'productId must be a valid integer.',
      }),
 	currentStock: Joi.number().integer().required().messages({
        'any.required': 'currentStock is required.',
        'number.base': 'currentStock must be a valid integer.',
      }),
 	previousStock: Joi.number().integer().required().messages({
        'any.required': 'previousStock is required.',
        'number.base': 'previousStock must be a valid integer.',
      })
});


/** Field references for clean, type-safe access */
const InventoryField = {
    Id: 'id',
    ProductId: 'product_id',
    CurrentStock: 'current_stock',
    PreviousStock: 'previous_stock',
    Createddate: 'createddate',
    All: ['id', 'product_id', 'current_stock', 'previous_stock', 'createddate'],
};


module.exports = {
  InventorySchema,
  InventoryField, 
};
