
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const InventoryHistorySchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	inventoryId: Joi.number().integer().required().messages({
        'any.required': 'inventoryId is required.',
        'number.base': 'inventoryId must be a valid integer.',
      }),
 	date: Joi.string().isoDate().required().messages({
        'any.required': 'date is required.',
        'string.empty': 'date must be a valid date.',
      }),
 	stockBefore: Joi.number().integer().required().messages({
        'any.required': 'stockBefore is required.',
        'number.base': 'stockBefore must be a valid integer.',
      }),
 	stockAfter: Joi.number().integer().required().messages({
        'any.required': 'stockAfter is required.',
        'number.base': 'stockAfter must be a valid integer.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const InventoryHistoryField = {
    Id: 'id',
    InventoryId: 'inventory_id',
    Date: 'date',
    StockBefore: 'stock_before',
    StockAfter: 'stock_after',
    Status: 'status',
    All: ['id', 'inventory_id', 'date', 'stock_before', 'stock_after', 'status'],
};


module.exports = {
  InventoryHistorySchema,
  InventoryHistoryField, 
};
