// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi')

const MasterAccessSchema = Joi.object({
  id: Joi.number().integer().required().messages({
    'any.required': 'id is required.',
    'number.base': 'id must be a valid integer.',
  }),
  name: Joi.string().trim().required().messages({
    'any.required': 'name is required.',
    'string.empty': 'name must be a valid string.',
  }),
  status: Joi.string().trim().required().messages({
    'any.required': 'status is required.',
    'string.empty': 'status must be a valid enum.',
  }),
})

/** Field references for clean, type-safe access */
const MasterAccessField = {
  Id: 'id',
  Name: 'name',
  Status: 'status',
  Createddate: 'createddate',
  All: ['id', 'name', 'status', 'createddate'],
}

module.exports = {
  MasterAccessSchema,
  MasterAccessField,
}
