
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterRouteSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	accessId: Joi.number().integer().required().messages({
        'any.required': 'accessId is required.',
        'number.base': 'accessId must be a valid integer.',
      }),
 	routeName: Joi.string().trim().required().messages({
        'any.required': 'routeName is required.',
        'string.empty': 'routeName must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const MasterRouteField = {
    Id: 'id',
    AccessId: 'access_id',
    RouteName: 'route_name',
    Status: 'status',
    Createddate: 'createddate',
    All: ['id', 'access_id', 'route_name', 'status', 'createddate'],
};


module.exports = {
  MasterRouteSchema,
  MasterRouteField, 
};
