
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const OrdersSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	date: Joi.string().isoDate().required().messages({
        'any.required': 'date is required.',
        'string.empty': 'date must be a valid date.',
      }),
 	customerId: Joi.number().integer().required().messages({
        'any.required': 'customerId is required.',
        'number.base': 'customerId must be a valid integer.',
      }),
 	total: Joi.string().trim().required().messages({
        'any.required': 'total is required.',
        'string.empty': 'total must be a valid decimal.',
      }),
 	paymentType: Joi.string().trim().required().messages({
        'any.required': 'paymentType is required.',
        'string.empty': 'paymentType must be a valid string.',
      }),
 	paymentReference: Joi.string().trim().required().messages({
        'any.required': 'paymentReference is required.',
        'string.empty': 'paymentReference must be a valid text.',
      }),
 	details: Joi.string().trim().required().messages({
        'any.required': 'details is required.',
        'string.empty': 'details must be a valid text.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const OrdersField = {
    Id: 'id',
    Date: 'date',
    CustomerId: 'customer_id',
    Total: 'total',
    PaymentType: 'payment_type',
    PaymentReference: 'payment_reference',
    Details: 'details',
    Status: 'status',
    All: ['id', 'date', 'customer_id', 'total', 'payment_type', 'payment_reference', 'details', 'status'],
};


module.exports = {
  OrdersSchema,
  OrdersField, 
};
