
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ProductSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
 	categoryId: Joi.number().integer().required().messages({
        'any.required': 'categoryId is required.',
        'number.base': 'categoryId must be a valid integer.',
      }),
 	price: Joi.string().trim().required().messages({
        'any.required': 'price is required.',
        'string.empty': 'price must be a valid decimal.',
      }),
 	cost: Joi.string().trim().required().messages({
        'any.required': 'cost is required.',
        'string.empty': 'cost must be a valid decimal.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const ProductField = {
    Id: 'id',
    Name: 'name',
    CategoryId: 'category_id',
    Price: 'price',
    Cost: 'cost',
    Status: 'status',
    Createddate: 'createddate',
    All: ['id', 'name', 'category_id', 'price', 'cost', 'status', 'createddate'],
};


module.exports = {
  ProductSchema,
  ProductField, 
};
