
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ProductImageSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	productId: Joi.number().integer().required().messages({
        'any.required': 'productId is required.',
        'number.base': 'productId must be a valid integer.',
      }),
 	image: Joi.string().trim().required().messages({
        'any.required': 'image is required.',
        'string.empty': 'image must be a valid text.',
      })
});


/** Field references for clean, type-safe access */
const ProductImageField = {
    Id: 'id',
    ProductId: 'product_id',
    Image: 'image',
    Createddate: 'createddate',
    All: ['id', 'product_id', 'image', 'createddate'],
};


module.exports = {
  ProductImageSchema,
  ProductImageField, 
};
