
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const RiderActivitySchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	riderId: Joi.number().integer().required().messages({
        'any.required': 'riderId is required.',
        'number.base': 'riderId must be a valid integer.',
      }),
 	deliveryId: Joi.number().integer().required().messages({
        'any.required': 'deliveryId is required.',
        'number.base': 'deliveryId must be a valid integer.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
 	date: Joi.string().isoDate().required().messages({
        'any.required': 'date is required.',
        'string.empty': 'date must be a valid date.',
      })
});


/** Field references for clean, type-safe access */
const RiderActivityField = {
    Id: 'id',
    RiderId: 'rider_id',
    DeliveryId: 'delivery_id',
    Status: 'status',
    Date: 'date',
    All: ['id', 'rider_id', 'delivery_id', 'status', 'date'],
};


module.exports = {
  RiderActivitySchema,
  RiderActivityField, 
};
